guideline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('guides.urls'), name='index'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guides/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'guides'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^sort/(?P<filter>[\w]+)/$', views.SortedIndexView.as_view(), name='index_sorted'),
    url(r'^section/(?P<section>[\w_-]+)/$', views.SectionView.as_view(), name='section'),
    url(r'^sections_browser/$', views.SectionBrowserView.as_view(), name='sections_browser'),
    url(r'^my_guides/$', login_required(views.MyGuidesView.as_view()), name='my_guides'),
    url(r'^(?P<pk>[0-9]+)/$', views.GuideView.as_view(), name='guide'),
    url(r'^vote_for_comment/$', login_required(views.vote_for_comment), name='vote_for_comment'),
    url(r'^create_guide/$', login_required(views.CreateGuideView.as_view()), name='create_guide'),
    url(r'^about_us/$', views.AboutUsView.as_view(), name='about_us'),
    url(r'^vote/$', login_required(views.vote), name='vote'),
    url(r'delete/$', login_required(views.delete_guide), name='delete_guide'),
    url(r'^edit/(?P<pk>[0-9]+)/$', login_required(views.EditGuideView.as_view()), name='edit_guide'),
]

guides/models.py
from django.db import models
from accounts.models import CustomUser
from ckeditor.fields import RichTextField


class Section(models.Model):
    section_name = models.CharField(max_length=50)

    def __str__(self):
        return self.section_name


class Tag(models.Model):
    tag = models.CharField(max_length=50)

    def __str__(self):
        return self.tag


class Guide(models.Model):
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    guide_name = models.CharField(max_length=100)
    description = models.CharField(max_length=255, blank=True)
    tags = models.ManyToManyField(Tag, related_name='guide_tags', blank=True)
    guide_text = RichTextField(config_name='guide_creation')
    pub_date = models.DateTimeField(auto_now_add=True)
    preview = models.CharField(max_length=255)
    author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    hidden = models.BooleanField(default=False)
    user_voted = models.ManyToManyField(CustomUser, related_name='guide_voted', blank=True)

    def __str__(self):
        return "{}. {} by {}".format(self.pk, self.guide_name, self.author)

    def convert_tags_to_string(self):
        tags_query = self.tags.all()
        tags_list = [tag_obj.tag for tag_obj in tags_query]
        tags_string = ', '.join(tags_list)
        return tags_string


class Comment(models.Model):
    comment_text = RichTextField(config_name='comment')
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    user_voted = models.ManyToManyField(CustomUser, related_name='comment_voted', blank=True)
    guide = models.ForeignKey(Guide, on_delete=models.CASCADE)

    def __str__(self):
        return "{} by {}".format(self.comment_text, self.author)

guides/forms.py
from django.forms import ModelForm
from django.core.exceptions import ObjectDoesNotExist
from .models import Guide, Section, Tag, Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

    def save(self, user, guide):
        comment = super(CommentForm, self).save(commit=False)
        comment.author = user
        comment.guide = guide
        comment.save()
        return comment


class GuideForm(ModelForm):
    class Meta:
        model = Guide
        fields = ['guide_name', 'description', 'preview', 'hidden', 'guide_text']

    def __init__(self, user, section, tags, *args, **kwargs):
        self.user = user
        self.section = section
        self.tags = tags
        super(GuideForm, self).__init__(*args, **kwargs)

    def save(self):
        guide = super(GuideForm, self).save(commit=False)
        guide.author = self.user
        guide.section = get_guide_section(self.section)
        guide.save()
        tags = get_tags_objects(self.tags)
        [guide.tags.add(tag) for tag in tags]
        return guide


def get_guide_section(section_name):
    # form have default value, it can be '', .get('section', default) did'n work in this case
    if not section_name:
        section_name = 'Other'
    try:
        section_object = Section.objects.get(section_name__iexact=section_name)
    except ObjectDoesNotExist:
        section_name = section_name.strip().capitalize()
        section_object = Section(section_name=section_name)
        section_object.save()
    return section_object


def get_tags_objects(tags_string):
    tags = set()
    tags_list = tags_string.split(',')
    tags_list = [tag.strip().capitalize() for tag in tags_list]
    for tag_name in tags_list:
        try:
            tag_object = Tag.objects.get(tag__iexact=tag_name)
        except ObjectDoesNotExist:
            tag_object = Tag(tag=tag_name)
            tag_object.save()
        tags.add(tag_object)
    return tags

guides/views.py
import datetime
from django.views import generic
from django.db.models import Count
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.urls import reverse
from .models import Guide, Section, Comment
from .forms import CommentForm, GuideForm, get_guide_section, get_tags_objects


class IndexView(generic.ListView):
    template_name = 'guides/index_content.html'
    context_object_name = 'guides_list'
    paginate_by = 15

    def get_queryset(self):
        return Guide.objects.filter(hidden=False).annotate(Count('user_voted'))

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['sections'] = Section.objects.annotate(num_guides=Count('guide'))[:10]
        return context


class SortedIndexView(IndexView):
    def get_queryset(self):
        guides_filter = self.kwargs.get('filter', None)
        if not guides_filter or guides_filter == 'top_all_time':
            guides = Guide.objects.filter(hidden=False).annotate(Count('user_voted'))
        elif guides_filter == "top_month":
            current_month = datetime.date.today().month
            current_year = datetime.date.today().year
            guides = Guide.objects.filter(pub_date__gte=datetime.date(current_year, current_month, 1), hidden=False)
            guides = guides.annotate(Count('user_voted'))
        elif guides_filter == 'new':
            guides = Guide.objects.filter(hidden=False).order_by("-pub_date")
        else:
            guides = []
        return guides


class SectionView(IndexView):
    def get_queryset(self):
        section_name = self.kwargs.get('section', None)
        section = Section.objects.get(section_name=section_name)
        return Guide.objects.filter(section=section, hidden=False).annotate(Count('user_voted'))


class SectionBrowserView(IndexView):
    paginate_by = None
    template_name = 'guides/sections_browser.html'
    context_object_name = 'sections_list'

    def get_queryset(self):
        return Section.objects.annotate(num_guides=Count('guide')).order_by('-num_guides')


class MyGuidesView(IndexView):
    template_name = 'guides/my_guides.html'

    def get_queryset(self):
        return Guide.objects.filter(author=self.request.user.pk).order_by('-pub_date')


class GuideView(generic.edit.FormMixin, generic.DetailView):
    model = Guide
    template_name = 'guides/guide.html'
    context_object_name = 'guide'
    form_class = CommentForm

    def get_success_url(self):
        return reverse('guides:guide', kwargs={'pk': self.object.pk}) + "#ckeditor"

    def get_context_data(self, **kwargs):
        context = super(GuideView, self).get_context_data(**kwargs)
        context['sections'] = Section.objects.annotate(num_guides=Count('guide'))[:10]
        context['comments'] = Comment.objects.filter(guide=self.object.pk)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save(self.request.user, self.object)
        return super(GuideView, self).form_valid(form)

    def form_invalid(self, form):
        return super(GuideView, self).form_invalid(form)

    def get_object(self, queryset=None):
        target_object = super(GuideView, self).get_object()
        if target_object.hidden and self.request.user != target_object.author:
            return None
        else:
            return target_object


class CreateGuideView(generic.edit.FormView):
    template_name = 'guides/guide_creation.html'
    form_class = GuideForm
    success_url = '/my_guides/'

    def get_form_kwargs(self):
        kwargs = super(CreateGuideView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['section'] = self.request.POST.get('section', 'Other')
        kwargs['tags'] = self.request.POST.get('tags', '')
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(CreateGuideView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CreateGuideView, self).get_context_data(**kwargs)
        sections_query = Section.objects.all()
        sections_list = [section.section_name for section in sections_query]
        context["existing_sections"] = sections_list
        context["action"] = 'create'
        return context


class EditGuideView(generic.edit.UpdateView):
    model = Guide
    fields = ['guide_name', 'description', 'preview', 'hidden', 'guide_text']
    template_name = 'guides/guide_creation.html'
    success_url = '/my_guides/'

    def dispatch(self, request, *args, **kwargs):
        guide = self.get_object()
        if guide.author != self.request.user:
            return HttpResponseRedirect(reverse('guides:guide', args=[guide.pk]))
        return super(EditGuideView, self).dispatch(request, *args, **kwargs)

    def save_tags(self, guide):
        guide.tags.clear()
        tags_objects_set = get_tags_objects(self.request.POST['tags'])
        [guide.tags.add(tag) for tag in tags_objects_set]

    def save_section(self, guide):
        section_name = self.request.POST['section']
        section_object = get_guide_section(section_name)
        guide.section = section_object
        guide.save()

    def form_valid(self, form):
        what_ever = super(EditGuideView, self).form_valid(form)
        guide = self.get_object()
        self.save_tags(guide)
        self.save_section(guide)
        return what_ever

    def get_context_data(self, **kwargs):
        context = super(EditGuideView, self).get_context_data(**kwargs)
        sections_query = Section.objects.all()
        sections_list = [section.section_name for section in sections_query]
        context["existing_sections"] = sections_list
        context["action"] = 'edit'
        return context


def vote_for_comment(request):
    referer = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        comment_pk = request.POST['comment_pk']
        target_comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user not in target_comment.user_voted.all():
            target_comment.user_voted.add(request.user)
        else:
            target_comment.user_voted.remove(request.user)
    return HttpResponseRedirect(referer + '#comment_{}'.format(target_comment.pk))


def vote(request):
    referer = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        guide_pk = request.POST['guide_pk']
        target_guide = get_object_or_404(Guide, pk=guide_pk)
        if request.user not in target_guide.user_voted.all():
            target_guide.user_voted.add(request.user)
        else:
            target_guide.user_voted.remove(request.user)
    return HttpResponseRedirect(referer + '#guide_{}'.format(target_guide.pk))


def delete_guide(request):
    if request.method == 'POST':
        guide_pk = request.POST['guide_pk']
        target_guide = get_object_or_404(Guide, pk=guide_pk)
        if target_guide.author == request.user:
            target_guide.delete()
    return HttpResponseRedirect(reverse('guides:my_guides'))


class AboutUsView(generic.TemplateView):
    template_name = 'guides/about_us.html'

    def get_context_data(self, **kwargs):
        context = super(AboutUsView, self).get_context_data(**kwargs)
        context['sections'] = Section.objects.annotate(num_guides=Count('guide'))[:10]
        return context

guides/templates/guides/guide.html
{% extends "guides/index_base.html" %}

{% block head %}
<head>
    <meta charset="utf-8">
    <title>Guide: {{ guide.guide_name }}</title>
    <meta name="description" content="guides guide">

    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'guides/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'guides/style.css' %}">
</head>
{% endblock %}

{% block content %}
<div class="page-content">
    <div class="guide">
        {% if guide %}
        <div class="title">
            <h3>{{ guide.guide_name }}</h3> by {{ guide.author }}
        </div>
        {% if user == guide.author %}
        <div class="edit-delete-menu">
            <hr>
            <a class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
               href="{% url 'guides:edit_guide' guide.pk %}">
                Edit guide
            </a>
            <a class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
               href="{% url 'guides:delete_guide' %}">
                Delete guide
            </a>
        </div>
        {% endif %}
        <hr>
        <p>{{ guide.guide_text|safe }}</p>
        {% else %}
        <div class="title">
            <h3>This guide is not available</h3>
        </div>
        {% endif %}
    </div>
    <div class="comments-area">
        <hr>
        {% for comment in comments %}
        <div class="comment">
            {% if user.is_authenticated %}
            <div class="comment-vote">
                <div class="votes">{{ comment.user_voted.all|length }}</div>
                <form action="{% url 'guides:vote_for_comment' %}" method="post" class="form-vote">
                    {% csrf_token %}
                    <input type="hidden" name="comment_pk" value="{{ comment.pk }}">
                    <input type="submit" class="hidden-button" id="vote_for_comment_{{ comment.pk }}">
                    <label for="vote_for_comment_{{ comment.pk }}">
                        <i class="material-icons comment-guide-icon">thumb_up</i>
                    </label>
                </form>
            </div>
            {% endif %}
            <a name="comment_{{ comment.pk }}" href="#comment_{{ comment.pk }}"></a>
            <div class="comment_author">
                 {{ comment.author }} posted at {{ comment.pub_date }}:
            </div>
            <div class="comment_text">
                {{ comment.comment_text|safe }}
            </div>
        </div>
        {% endfor %}
        {% if user.is_authenticated %}
        <a name="ckeditor" href="#ckeditor"></a>
        <div class="comment-create">
            <form action="{% url 'guides:guide' guide.pk %}" method="POST">
                {% csrf_token %}
                {{ form.media }}
                {{ form.comment_text }}
                <input type="submit" value="Submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored"/>
            </form>
        </div>
        {% endif %}

    </div>
</div>
{% endblock %}

guides/templates/guides/guide_creation.html
{% extends "guides/header.html" %}

{% block head %}
<head>
    <meta charset="utf-8">
    <title>Guide creation</title>
    <meta name="description" content="guides guide">

    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'guides/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'guides/style.css' %}">
</head>
{% endblock %}

{% block main %}
{% load widget_tweaks %}
<div class="guide_creation">
    {% if action == 'create' %}
    <form action="{% url 'guides:create_guide' %}" method="post" enctype="multipart/form-data" autocomplete="off">
    {% else %}
    <form action="{% url 'guides:edit_guide' guide.pk %}" method="post" enctype="multipart/form-data" autocomplete="off">
    {% endif %}
        {% csrf_token %}
        {{ form.media }}

        <div class="mdl-textfield mdl-js-textfield">
            {{ form.guide_name|add_class:"mdl-textfield__input" }}
            <label for="{{ form.guide_name.id_for_label }}" class="mdl-textfield__label">Guide name</label>
        </div>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield_description">
            {{ form.description|add_class:"mdl-textfield__input" }}
            <label for="{{ form.description.id_for_label }}" class="mdl-textfield__label">Short description</label>
        </div>

        <div class="mdl-textfield mdl-js-textfield form-tags">
            <input type="text" id="tags" name="tags" class="mdl-textfield__input" value="{{ guide.convert_tags_to_string }}">
            <label for="tags" class="mdl-textfield__label">Tags (Example: tag_1, tag two, ...)</label>
        </div>

        <div class="autocomplete mdl-textfield mdl-js-textfield form-section">
            <input type="text" id="section" name="section" class="mdl-textfield__input" value="{{ guide.section }}">
            <label for="section" class="mdl-textfield__label">Section</label>
        </div>

        <div class="mdl-textfield mdl-js-textfield">
            {{ form.preview|add_class:"mdl-textfield__input" }}
            <label for="{{ form.preview.id_for_label }}" class="mdl-textfield__label">Preview image url (H:W 170:320 px)</label>
        </div>

        <br />

        <div class="form-hidden">
            <label class="mdl-switch mdl-js-switch mdl-js-ripple-effect" for="{{ form.hidden.id_for_label }}">
                {{ form.hidden|add_class:"mdl-switch__input" }}
                <span class="mdl-switch__label">Hidden</span>
            </label>
        </div>

        <p>{{ form.guide_text }}</p>

        <input type="submit" value="Submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored"/>
    </form>

    <!-- Autocomplete for section input -->
    <script src="{% static 'guides/autocomplete.js' %}"></script>
    <script>
        var countries = {{ existing_sections|safe }};
        autocomplete(document.getElementById("section"), countries);
    </script>
    </form>
</div>
{% endblock %}

guides/templates/guides/header.html
<!DOCTYPE html>
<html lang="en">
{% block head %}
{% endblock %}

<body>
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

    <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
            <a class="mdl-layout-title" href="{% url 'guides:index' %}">Guideline</a>
            <!-- Add spacer, to align navigation to the right -->
            <div class="mdl-layout-spacer"></div>
            <nav class="mdl-navigation mdl-layout--large-screen-only">
                {% load socialaccount %}
                {% if user.is_authenticated %}
                <button id="demo-menu-lower-left" class="mdl-button mdl-js-button mdl-button--icon">
                    <i class="material-icons">more_vert</i>
                </button>
                <ul class="mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect"
                    for="demo-menu-lower-left">
                    <li class="mdl-menu__item"><a href="{% url 'account_logout' %}">Sign Out</a></li>
                    <li class="mdl-menu__item"><a href="{% url 'guides:my_guides' %}">My guides</a></li>
                    <li class="mdl-menu__item"><a href="{% url 'guides:create_guide' %}">Create new guide</a></li>
                </ul>
                <span class="mdl-navigation__link">Hi, {{ user.username }}</span>
                {% else %}
                <a class="mdl-navigation__link" href="{% url 'account_login' %}">Sign In</a>
                {% endif %}
                <a class="mdl-navigation__link" href="{% url 'guides:about_us' %}">About site</a>
            </nav>
        </div>
    </header>

    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Guideline</span>
        <nav class="mdl-navigation">
            {% if user.is_authenticated %}
            <a class="mdl-navigation__link" href="{% url 'account_logout' %}">Sign Out</a>
            <a class="mdl-navigation__link" href="{% url 'guides:my_guides' %}">My guides</a>
            <a class="mdl-navigation__link" href="{% url 'guides:create_guide' %}">Create new guide</a>
            {% else %}
            <a class="mdl-navigation__link" href="{% url 'account_login' %}">Sign In</a>
            {% endif %}
            <a class="mdl-navigation__link" href="{% url 'guides:about_us' %}">About site</a>
        </nav>
    </div>

    {% block main %}
    {% endblock %}
</div>
<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
</body>
</html>

guides/templates/guides/index_base.html
{% extends "guides/header.html" %}

{% block head %}
{% endblock %}

{% block main %}
<main class="mdl-layout__content">
    <!-- Left side menu. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer">
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">Sections</span>
            <nav class="mdl-navigation">
                {% for section in sections %}
                <a class="mdl-navigation__link" href="{% url 'guides:section' section.section_name %}">
                    {{ section.section_name }}
                </a>
                {% endfor %}
                <a class="mdl-navigation__link" href="{% url 'guides:sections_browser' %}">All sections</a>
            </nav>
            <span class="mdl-layout-title">By polularity</span>
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" href="{% url 'guides:index_sorted' 'top_month' %}">
                    Top guides of the month
                </a>
                <a class="mdl-navigation__link" href="{% url 'guides:index_sorted' 'top_all_time' %}">
                    Top of all time
                </a>
                <a class="mdl-navigation__link" href="{% url 'guides:index_sorted' 'new' %}">
                    New
                </a>
            </nav>
        </div>
    </div>

    {% block content %}
    {% endblock %}

    {% if is_paginated %}
    <div class="pagination">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="page-button">&laquo;</a>
        {% else %}
        <a href="" class="page-button disabled">&laquo;</a>
        {% endif %}

        {% if page_obj.number|add:'-4' > 1 %}
        <a href="?page=1">1</a>
        <a href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a>
        {% endif %}

        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <a href="#" class="page-button active">{{ i }}</a>
        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
        <a href="?page={{ i }}">{{ i }}</a>
        {% endif %}
        {% endfor %}

        {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
        <a href="?page={{ page_obj.number|add:'5' }}">&hellip;</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="page-button">&raquo;</a>
        {% else %}
        <a href="" class="disabled page-button">&raquo;</a>
        {% endif %}
    </div>
    {% endif %}
</main>
{% endblock %}

guides/templates/guides/index_content.html
{% extends "guides/index_base.html" %}

{% block head %}
<head>
    <meta charset="utf-8">
    <title>Guides</title>
    <meta name="description" content="guides guide">

    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'guides/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'guides/style.css' %}">
</head>
{% endblock %}

{% block content %}
<div class="page-content grid-container">
    <div class="main-sector-1">
        {% for guide in guides_list %}
        <div class="card-square">
            <a name="guide_{{ guide.pk }}" href="#guide_{{ guide.pk }}"></a>
            <a href="{% url 'guides:guide' guide.pk %}">
                <div class="card-preview">
                    <img src="{{ guide.preview }}">
                </div>
                <div class="card-description">
                    <h5>{{ guide.guide_name }}</h5>
                    <p>{{ guide.description }}</p>
                </div>
            </a>
            <div class="card-buttons">
                {% if user.is_authenticated %}
                <form action="{% url 'guides:vote' %}" method="post" class="form-vote">
                    {% csrf_token %}
                    <input type="hidden" name="guide_pk" value="{{ guide.pk }}">
                    <input type="submit" class="hidden-button" id="vote_for_guide_{{ guide.pk }}">
                    <label for="vote_for_guide_{{ guide.pk }}">
                        {% if user not in guide.user_voted.all %}
                        <i class="material-icons vote-guide-icon">favorite_border</i>
                        {% else %}
                        <i class="material-icons vote-guide-icon">favorite</i>
                        {% endif %}
                    </label>
                </form>
                <div class="votes">
                    {{ guide.user_voted.all|length }}
                </div>
                {% else %}
                <i class="material-icons vote-guide-icon">favorite_border</i>
                <div class="votes">
                    {{ guide.user_voted.all|length }}
                </div>
                {% endif %}
                {% block buttons %}
                {% endblock %}
            </div>
        </div>
        {% endfor %}
        {% block extracards %}
        {% endblock %}
    </div>
</div>
{% endblock %}

guides/templates/guides/my_guides.html
{% extends "guides/index_content.html" %}

{% block head %}
<head>
    <meta charset="utf-8">
    <title>My guides</title>
    <meta name="description" content="guides guide">

    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'guides/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'guides/style.css' %}">
</head>
{% endblock %}

{% block buttons %}
<div class="delete-button">
    <form action="{% url 'guides:delete_guide' %}" method="post" class="form-delete">
        {% csrf_token %}
        <input type="hidden" name="guide_pk" value="{{ guide.pk }}">
        <input type="submit" class="hidden-button" id="delete_guide_{{ guide.pk }}">
        <label for="delete_guide_{{ guide.pk }}">
            <i class="material-icons delete-guide-icon">delete</i>
        </label>
    </form>
</div>
<div class="edit-button">
    <a href="{% url 'guides:edit_guide' guide.pk %}"><i class="material-icons">edit</i></a>
</div>
{% endblock %}

{% block extracards %}
<!-- Карточка для создания нового гайда -->
<div class="card-square">
    <a href="{% url 'guides:create_guide' %}">
        <div class="card-preview">
            <img src="{% static 'guides/work.png' %}">
        </div>
        <div class="card-description">
            <h5>Create a new awesome guide!</h5>
            <p>Just do it!<br>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" 			    title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
            </p>
        </div>
    </a>
    <div class="card-buttons">
        <i class="material-icons vote-guide">favorite</i>
    </div>
</div>
{% endblock %}